apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: consumer-sqs
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      container:
        image: jonatasbaldin/consumer-sqs
